### ISSUE TITLE
Music license

### ISSUE THREAD

**Issue by akien-mga** [TeddyDD/Gravity-Hates-You#1]
Hi @TeddyDD, thanks to you and your girlfriend for this cool game :)

You mention in the LICENSE.md that the music is "Reformat" by Kevin MacLeod. At first I feared that it would be yet another "royalty-free but no license" track, but actually looking at the given link, it seems to be CC By 3.0:

> Reformat by Kevin MacLeod is licensed under CC Attribution 3.0.

Could you add this info to the license?

_Edit:_ Actually I've done a PR using GH's web editor.

**Comment by akien-mga** [comment]
While I'm asking about licensing: is the choice of CC By-NC 3.0 for your girlfriend's artwork a strongly-motivated choice?

If not, as a free software and free culture aficionado, I can only advise to consider CC By-SA 3.0 instead, as the NC clause is not so well-liked in the free software community; it brings into a very badly-defined grey area as "commercial usage" is very broad.

For example, selling a magazine with a DVD spin of a Linux distro which contains among many other things a packaged game using this artwork could be considered a commercial usage of this artwork. So Linux distros will outright ban any NC content from their "free" repositories. Debian, Fedora and Mageia for example consider any NC license "nonfree".

Well, that's it for my "set it free" plea :P There are tons of articles on the Internet as to why NC makes CC hardly better than an unbranded "freeware" if you're interested.

**Comment by TeddyDD** [comment]
> You mention in the LICENSE.md that the music is "Reformat" by Kevin MacLeod. At first I feared that it would be yet another "royalty-free but no license" track, but actually looking at the given link, it seems to be CC By 3.0

Thanks a lot! I had remembered to add this mention to in-game credits but I forgot about LICENSE.md silly me :)

I am fully aware that CC-BY-NC license its not very popular in terms of free culture and sometimes it cause trouble. However my GF is not very convinced to change license for now and I think in case it's not an issue. It's more like learning resource than full game that someone would like to ship with some Linux distro or magazine. If the license become an issue in the future we will reconsider this :)

**Comment by akien-mga** [comment]
> However my GF is not very convinced to change license for now and I think in case it's not an issue.

Indeed, I also think it's not a big deal here. Just wanted to make sure you're aware of what the license entails :)
